### ISSUE TITLE
Clarify what it actually does

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/ReflectOnMee#1]
Please describe it in more detail.  As soon as it starts to enforce the pause, it seems almost random when and why it happens, even though I have small numbers in the options.

**Comment by lovac42** [comment]
It prevents you from clicking on the buttons. So if you set a limit of 5 and 10. After 5 sec, it will pause for 10 sec. If it takes you more than 5 sec to click "show answer" it will enforce a pause of 10 sec, forcing you to reflect on the card. Learning cards are enforced for at least 3 secs regardless (if it's turned on, non zero).

**Comment by aleksejrs** [comment]
> If it takes you more than 5 sec to click "show answer" it will enforce a pause of 10 sec, forcing you to reflect on the card.

I guess that's not useful for me then. Sometimes I choose the rating before pressing Space. So I thought it was the opposite. Maybe I should set it to something like 60 and 1.

**Comment by lovac42** [comment]
Yeah this is to force you to think about your errors and not pass it off as a fart.

**Comment by aleksejrs** [comment]
> Sometimes I choose the rating before pressing Space.

Oh, I didn't realize that meant not seeing the answer. Will think about it later.
